// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvdydmknpgweohnwbpeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2ZHlkbWtucGd3ZW9obndicGVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzMzMTUsImV4cCI6MjA3MDYwOTMxNX0.WN8NayX22TY2TUKiLe5ojOkqkrW61B6dOAV9oqEjI7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});